name: OPMenu
main: net.l_bulb.opmenu.OpMenu
version: 1.0.0
commands:
  fly:
    description: FlyMode
    usage: /<command>
    permission: staff.fly
  menu:
    description: Menu
    usage: /<command>
    permission: staff.menu
  staff:
    description: Staff
    usage: /<command>
    permission: staff.staff